# Generated by Django 3.2.6 on 2022-03-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentschedule',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
