# Generated by Django 3.2.6 on 2022-05-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_alter_recruitmentschedule_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentschedule',
            name='end',
        ),
        migrations.RemoveField(
            model_name='recruitmentschedule',
            name='location',
        ),
        migrations.RemoveField(
            model_name='recruitmentschedule',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recruitmentschedule',
            name='start',
        ),
    ]
