# Generated by Django 3.2.6 on 2022-07-01 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '__first__'),
        ('recruitment', '0002_alter_recruitmentschedule_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentschedule',
            name='end',
        ),
        migrations.RemoveField(
            model_name='recruitmentschedule',
            name='location',
        ),
        migrations.RemoveField(
            model_name='recruitmentschedule',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recruitmentschedule',
            name='start',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='recruitmentschedule',
            name='d_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruitmentschedule',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_schedule', to='schedule.schedule'),
        ),
        migrations.AlterField(
            model_name='recruitmentschedule',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_schedule', to='recruitment.recruitment'),
        ),
    ]
