# Generated by Django 3.2.6 on 2022-09-14 19:28

from django.db import migrations, models
import django.db.models.deletion
import sharkle.upload_image


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_recruitment_title_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentInfoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_image', models.ImageField(upload_to=sharkle.upload_image.upload_image)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_image', to='recruitment.recruitment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
