# Generated by Django 3.2.6 on 2022-05-11 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('recruitment', '0003_auto_20220511_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentschedule',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_schedule', to='schedule.schedule'),
        ),
        migrations.AlterField(
            model_name='recruitmentschedule',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_schedule', to='recruitment.recruitment'),
        ),
    ]
