# Generated by Django 3.2.6 on 2022-07-02 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('recruitment', '0003_auto_20220701_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentschedule',
            name='schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_schedule', to='schedule.schedule'),
        ),
    ]
