# Generated by Django 3.2.6 on 2022-09-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_recruitmentinfoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentinfoimage',
            name='sequence',
            field=models.IntegerField(default=-1),
        ),
    ]
