# Generated by Django 3.2.6 on 2022-05-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_auto_20220511_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentschedule',
            name='d_day',
            field=models.BooleanField(default=False),
        ),
    ]
