# Generated by Django 3.2.6 on 2022-05-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_recruitmentschedule_d_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
