# Generated by Django 3.2.6 on 2022-02-24 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manager_editable', models.BooleanField(default=False)),
                ('allow_anonymous', models.BooleanField(default=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='circle.circle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
