# Generated by Django 3.2.6 on 2022-03-15 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0001_initial'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='circle',
        ),
        migrations.AddField(
            model_name='board',
            name='circle_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='circle.circle'),
            preserve_default=False,
        ),
    ]
