# Generated by Django 3.2.6 on 2022-03-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20220315_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='circle_id',
            new_name='circle',
        ),
        migrations.AlterField(
            model_name='board',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
