# Generated by Django 3.2.6 on 2022-03-19 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0001_initial'),
        ('board', '0003_auto_20220316_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='circle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='circle.circle'),
        ),
    ]
