# Generated by Django 3.2.6 on 2022-05-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_board_circle'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, '일반'), (1, '갤러리')], default=0),
        ),
    ]
