# Generated by Django 3.2.6 on 2022-07-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_circle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercirclealarm',
            name='live_recruitment_alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserRecruitmentAlarm',
        ),
    ]
