# Generated by Django 3.2.6 on 2022-07-26 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercircle_member',
            name='circle',
        ),
        migrations.RemoveField(
            model_name='usercircle_member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='make_new_member',
        ),
        migrations.DeleteModel(
            name='UserCircle_Alarm',
        ),
        migrations.DeleteModel(
            name='UserCircle_Member',
        ),
    ]
