# Generated by Django 3.2.6 on 2022-07-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='make_new_member',
            field=models.PositiveSmallIntegerField(choices=[(0, '기타'), (1, '학술/매체'), (2, '연행/예술'), (3, '취미/교양'), (4, '무예/운동'), (5, '인권/봉사'), (6, '종교')], default=1),
        ),
        migrations.AlterField(
            model_name='circle',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
