# Generated by Django 3.2.6 on 2022-07-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='introduction',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
