# Generated by Django 3.2.6 on 2022-09-14 16:10

from django.db import migrations, models
import sharkle.upload_image


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0002_auto_20220726_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='profile',
            field=models.ImageField(null=True, upload_to=sharkle.upload_image.upload_image),
        ),
    ]
