# Generated by Django 3.2.6 on 2022-07-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0002_auto_20220701_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='make_new_member',
            field=models.PositiveSmallIntegerField(choices=[(0, '일반'), (1, '회원'), (2, '관리자')], default=1),
        ),
    ]
