# Generated by Django 3.2.6 on 2022-07-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
